name: Update Submodules

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Update Submodules
        run: git submodule update --remote --recursive
