name: Update Submodules

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{ secrets.GH_ACTIONS_TOKEN }}
          submodules: true
          repository: org/Study
        
      - name: Update Submodules
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git commit -am "Update 백준"
          git push
