name: Update Submodules

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{ secrets.GH_ACTIONS_TOKEN }}
          submodules: true
        
      - name: Update Submodules
        run: |
          git submodule update --remote --recursive
          git config --global user.email "rlatjwls7882@gmail.com"
          git config --global user.name "rlatjwls7882"
          git commit -m "Update 백준"
          git push origin main
